server:
  port: 8082

spring:
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
        useConfigs: maxPerformance
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/develop
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: 'off'
  jpa:
    properties:
      hibernate:
        order_inserts: true
        order_update: true
        generate_statistics: true
        jdbc:
          batch_size: 60
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        cache: trace
        web: DEBUG
    root: WARN
    transaction:
      interceptor: info

cbr:
  thesaurusUrl: "http://www.cbr.ru/scripts/XML_valFull.asp"
  quotesUrl: "http://cbr.ru/scripts/XML_daily.asp"
